xssssss---
title: "Hosp Data Inspection"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
pacman::p_load(plotly, tidyverse, gridExtra, RColorBrewer)
knitr::opts_chunk$set(echo = TRUE)
if(!(exists("full_scrape"))){
  source("~/Desktop/git/cov_nowcast_hosp/pull_sources.R")
}
```

## Visualizing Outcome by State

``` {r}
p <- lapply(unique(national_hosps$state), function(state_nm){
  ggplot(data = national_hosps %>% filter(state == state_nm), 
         aes(x = date, y = hospitalizations, color = state, group = state)) + 
    geom_point() + 
    labs(title = paste0('State: ', state_nm))
})
```

```{r}
for(set in seq(1, length(p), 4)){
  do.call(grid.arrange,p[set:min(set+3, length(p))])
}
```

## Visualizing Inputs

### Wastewater Data

```{r}
full_scrape$NWSS_Wastewater_Metric %>% head()
```

```{r}
nwss <- full_scrape$NWSS_Wastewater_Metric %>%
  select(date = date_end, state = wwtp_jurisdiction, sample_location, detect_prop_15d) %>% 
  group_by(date, state, sample_location) %>%
  summarise(avg_detect = mean(detect_prop_15d, na.rm = T), .groups = "keep")

nwss_plots <- lapply(unique(nwss$state), function(state_nm){
  ggplot(data = nwss %>% filter(state == state_nm), 
         aes(x = date, y = avg_detect, group = sample_location, color = sample_location)) + 
    geom_point() + 
    labs(title = paste0('State: ', state_nm))
})
```
```{r}
for(set in seq(1, length(nwss_plots), 4)){
  do.call(grid.arrange,nwss_plots[set:min(set+3, length(nwss_plots))])
}

```


### Wastewater Data

```{r}
full_scrape$NWSS_Wastewater_Metric %>% 
  select(wwtp_jurisdiction:key_plot_id) %>%
  distinct() %>%
  full_join(full_scrape$NWSS_Concentration) %>% head()
```

```{r}
nwss <- full_scrape$NWSS_Wastewater_Metric %>% 
  select(wwtp_jurisdiction:key_plot_id) %>%
  distinct() %>%
  full_join(full_scrape$NWSS_Concentration) %>% 
  select(date, state = wwtp_jurisdiction, sample_location, pcr_conc_lin) %>% 
  group_by(date, state, sample_location) %>%
  summarise(avg_detect = mean(pcr_conc_lin, na.rm = T), .groups = "keep")

nwss_plots <- lapply(unique(nwss$state), function(state_nm){
  ggplot(data = nwss %>% filter(state == state_nm), 
         aes(x = date, y = avg_detect, group = sample_location, color = sample_location)) + 
    geom_point() + 
    labs(title = paste0('State: ', state_nm))
})
```


```{r}
for(set in seq(1, length(nwss_plots), 4)){
  do.call(grid.arrange,nwss_plots[set:min(set+3, length(nwss_plots))])
}

```

### NSSP ED Visits

```{r}
full_scrape$NSSP_ED_Visit_Trajectory %>% head()
```

```{r}
nssp <- full_scrape$NSSP_ED_Visit_Trajectory %>% filter(county == "All") %>% 
  select(date = week_end, state = geography, percent_visits_covid)

nssp_plots <- lapply(unique(nssp$state), function(state_nm){
  ggplot(data = nssp %>% filter(state == state_nm), 
         aes(x = date, y = percent_visits_covid, group = state)) + 
    geom_point() + 
    labs(title = paste0('State: ', state_nm))
})
```
```{r}
for(set in seq(1, length(nssp_plots), 4)){
  do.call(grid.arrange,nssp_plots[set:min(set+3, length(nssp_plots))])
}
```


### NRVESS Test Data

```{r}
full_scrape$NRVESS_Test_Positivity %>% head()
```

```{r}
nvss_tp <- full_scrape$NRVESS_Test_Positivity %>% 
  select(date = mmwrweek_end, level, percent_pos, number_tested)

nvss_tp_plots <- lapply(unique(nvss_tp$level), function(level_nm){
  ggplot(data = nvss_tp %>% filter(level == level_nm), 
         aes(x = date, y = percent_pos, group = level)) + 
    geom_point() + 
    labs(title = paste0('Level: ', level_nm))
})
```
```{r}
for(set in seq(1, length(nvss_tp_plots), 3)){
  do.call(grid.arrange,nvss_tp_plots[set:min(set+2, length(nvss_tp_plots))])
}
```


### MakeMyTestCount Self Test Data

```{r}
full_scrape$MakeMyTestCount %>% head()
```

```{r}
mmtc <- full_scrape$MakeMyTestCount %>% 
  select(date, state, test_result, total_tests) %>%
  group_by(date, state, test_result) %>%
  summarise(total_tests = sum(total_tests, na.rm = T)) %>%
  ungroup() %>%
  pivot_wider(names_from = test_result, values_from = total_tests, 
              values_fill = 0) %>%
  rowwise() %>%
  mutate(pct_positive = Positive/(Positive + Negative))

mmtc_plots <- lapply(unique(mmtc$state), function(state_nm){
  ggplot(data = mmtc %>% filter(state == state_nm), 
         aes(x = date, y = pct_positive, group = state)) + 
    geom_point() + 
    labs(title = paste0('State: ', state_nm))
})
```
```{r}
for(set in seq(1, length(mmtc_plots), 4)){
  do.call(grid.arrange,mmtc_plots[set:min(set+3, length(mmtc_plots))])
}
```

### Variant Proprtions


```{r}
  full_scrape$NRVESS_Var_Props %>% 
  filter(modeltype == "weighted", count_lt10 %in% c('0', '0.0'), 
         week_ending >= '2022-07-01', time_interval == 'biweekly') %>% 
  head()
```

```{r}
var_props <- full_scrape$NRVESS_Var_Props %>% 
  filter(modeltype == "weighted", count_lt10 %in% c('0', '0.0'), 
         week_ending >= '2022-07-01', time_interval == 'biweekly', 
         creation_date == max(creation_date)) %>%
  select(date = week_ending, usa_or_hhsregion, variant, share) %>%
  mutate(variant = gsub( "(^[^.]+[.][^.]+)(.+$)", "\\1", variant)) %>%
  group_by(date, usa_or_hhsregion, variant) %>%
  summarise(share = sum(share, na.rm = T))

ggplot(data = var_props, 
         aes(x = date, y = share, fill = variant)) + 
    geom_bar(position="stack", stat="identity") + 
    facet_wrap(usa_or_hhsregion ~ .)

```

# CCF of data and outcome

## Combine datasets

```{r}

hospitalizations_age <- hospitalizations_age %>%
  #add HHS region to hospitalizations to map NVSS TP
  mutate(level = case_when(grepl('CT|ME|MA|NH|RI|VT', state) ~ 'Region 1', 
                           grepl('NJ|NY|PR|VI', state) ~ 'Region 2', 
                           grepl('DE|DC|MD|PA|VA|WV', state) ~ 'Region 3',
                           grepl('AL|FL|GA|KY|MS|NC|SC|TN', state) ~ 'Region 4',
                           grepl('IL|IN|MI|MN|OH|WI', state) ~ 'Region 5', 
                           grepl('AR|LA|NM|OK|TX', state) ~ 'Region 6', 
                           grepl('IA|KS|MO|NE', state) ~ 'Region 7', 
                           grepl('CO|MT|ND|SD|UT|WY', state) ~ 'Region 8', 
                           grepl('AZ|CA|HI|NV|AS|GU|MP', state) ~ 'Region 9', 
                           grepl('AK|ID|OR|WA', state) ~ 'Region 10', 
                           state == 'USA' ~ 'National',
                           T ~ 'UNMAPPED'))

nvss_tp <- full_scrape$NRVESS_Test_Positivity %>% 
  mutate(date = as.Date(mmwrweek_end), 
         mmwr = MMWRweek::MMWRweek(date), 
         mmwr_date = paste0(mmwr$MMWRyear, '-', 
                     if_else(nchar(mmwr$MMWRweek) == 1, paste0("0", 
                        mmwr$MMWRweek),  as.character(mmwr$MMWRweek)))) %>%
    select(date, level, percent_pos, number_tested, mmwr_date, posted) %>%
  mutate(count_pos = percent_pos * number_tested) %>%
  group_by(date, level) %>%
  filter(posted== max(posted)) %>%
  ungroup() %>%
  distinct()

states <- state.abb %>% bind_cols(state.name) %>%
  bind_rows(list(`...1` = 'DC', `...2` = 'District of Columbia')) %>%
  bind_rows(list(`...1` = 'USA', `...2` = 'United States'))
colnames(states) <- c('state', 'geography')
nssp <- full_scrape$NSSP_ED_Visit_Trajectory %>% 
  filter(county == "All") %>% 
  mutate(date = as.Date(week_end), 
         mmwr = MMWRweek::MMWRweek(date), 
         mmwr_date = paste0(mmwr$MMWRyear, '-', 
                     if_else(nchar(mmwr$MMWRweek) == 1, paste0("0", 
                        mmwr$MMWRweek),  as.character(mmwr$MMWRweek)))) %>%
  left_join(states) %>%
  select(ed_visit_date = date, state, geography, percent_visits_covid, mmwr_date)

nwss <- full_scrape$NWSS_Wastewater_Metric %>% 
  select(wwtp_jurisdiction:key_plot_id, population_served, date = date_end,
         detect_prop_15d) %>%
  distinct() %>%
  full_join(full_scrape$NWSS_Concentration) %>% 
  filter(sample_location == 'Treatment plant')  %>% 
  mutate(date = as.Date(date), 
         mmwr = MMWRweek::MMWRweek(date), 
         mmwr_date = paste0(mmwr$MMWRyear, '-', 
                     if_else(nchar(mmwr$MMWRweek) == 1, paste0("0", 
                        mmwr$MMWRweek),  as.character(mmwr$MMWRweek)))) %>%
  select(!sample_location_specify) %>%
  drop_na() %>%
  select(state = wwtp_jurisdiction, key_plot_id, mmwr_date, pcr_conc_lin,
         population_served, detect_prop_15d) %>% 
  # Frist by site
  group_by(state, mmwr_date, key_plot_id) %>%
  summarise(pop_served = mean(population_served, na.rm = T), 
            avg_detect_prop_15 = mean(detect_prop_15d, na.rm = T),
            avg_detect = mean(pcr_conc_lin, na.rm = T), .groups = "keep") %>%
  group_by(state, mmwr_date) %>%
  # then by state
  summarise(total_pop = sum(pop_served, na.rm = T), 
            avg_detect_prop_15 = mean(avg_detect_prop_15, na.rm = T),
            avg_detect = mean(avg_detect, na.rm = T)/total_pop, .groups = "keep") %>%
  ungroup() %>%
  rename(geography = state) %>%
    left_join(states) %>%
  select(!geography)

joined_df <- hospitalizations_age %>%
  left_join(nvss_tp, by = c('level', 'mmwr_date', 'date')) %>%
  left_join(nssp, by = c('state', 'mmwr_date')) %>%
  left_join(nwss, by = c('state', 'mmwr_date')) %>%
  filter(date <= "2024-05-01")


get_ccf <- function(df, state_nm){
  print(state_nm)
  filtered_df <- df %>% 
    filter(state == state_nm) 

  nvss = filtered_df %>%
    select(state, date, percent_pos, count_pos, 
           total_admissions_all_covid_confirmed) %>%
    drop_na()
  
  ed = filtered_df %>%
    select(state, date, percent_visits_covid, 
           total_admissions_all_covid_confirmed) %>%
    drop_na()
  
  nwss = filtered_df %>%
    select(state, date, avg_detect_prop_15, avg_detect, 
           total_admissions_all_covid_confirmed) %>%
    drop_na()

  pct_pos = ccf(nvss$percent_pos,
                nvss$total_admissions_all_covid_confirmed,
                plot = F)
  count_pos = ccf(nvss$count_pos,
                  nvss$total_admissions_all_covid_confirmed, 
                na.action = na.pass, plot = F)
  
  if(state_nm == 'MO'){
    ed_visit = list(acf = 0, lag = 0)
  } else {
      ed_visit = ccf(ed$percent_visits_covid,
                  ed$total_admissions_all_covid_confirmed, 
                na.action = na.pass, plot = F)

  }

  if(state_nm == 'ND' | state_nm == "RI" | state_nm == 'DC'){
    avg_detect_prop_15 = list(acf = 0, lag = 0)
    avg_detect = list(acf = 0, lag = 0)
  } else {
      avg_detect_prop_15 = ccf(nwss$avg_detect_prop_15,
                  nwss$total_admissions_all_covid_confirmed, 
                na.action = na.pass, plot = F)
      avg_detect = ccf(nwss$avg_detect,
                  nwss$total_admissions_all_covid_confirmed, 
                na.action = na.pass, plot = F)
  }
  tibble("acf" = pct_pos$acf, "lag" = pct_pos$lag, "type" = '% Positive') %>%
    bind_rows(tibble("acf" = count_pos$acf, "lag" = count_pos$lag,
                    "type" = 'Count Positive')) %>%
    bind_rows(tibble("acf" = ed_visit$acf, "lag" = ed_visit$lag,
                    "type" = 'ED Visit')) %>%
    bind_rows(tibble("acf" = avg_detect_prop_15$acf, 
                    "lag" = avg_detect_prop_15$lag,
                    "type" = 'WW % Detect')) %>%
    bind_rows(tibble("acf" = avg_detect$acf, 
                    "lag" = avg_detect$lag,
                    "type" = 'WW Detect')) %>%
    arrange(desc(acf)) %>%
    slice_head(n = 1, by = "type") %>%
    mutate(state = state_nm)
}

state_ccf= lapply(states$state, function(st){
  if(st == "USA"){
    return()
  } else {
    get_ccf(joined_df, st)
  }
}) %>%
  bind_rows()
```


```{r}
ccf_df <- state_ccf %>% 
  select(state, type, acf) %>%
  ungroup()  # %>%
#   pivot_wider(names_from = "type", values_from = "acf") %>%
#   as.data.frame()
# 
# rownames(ccf_df) = ccf_df$state
# ccf_df <- as.matrix(select(ccf_df, !state))
# 
# heatmap(ccf_df, Colv = NA, Rowv = NA, scale="column", 
#         col= colorRampPalette(brewer.pal(8, "YlGnBu"))(25))
#         
p <- ggplot(ccf_df, aes(x = state, y = type, fill = acf)) + 
  geom_tile() + 
  scale_fill_distiller("Correlation", palette = "RdYlBu") +
  theme_minimal() +
  theme(axis.title.y = element_blank(), 
        axis.title.x = element_blank(), 
        axis.text.x = element_text(angle = 0.45))
ggsave(paste0("results/CCF Heatmap.pdf"),
         plot = p, width = 16, height = 10, units = "in", bg = "white", 
         dpi = "retina")

write.csv(state_ccf, 'ccf.csv')
write_csv(joined_df %>% select(!mmwr), 'joined_df.csv')
```